### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by albertyou2** [sabhiram/raspberry-wifi-conf#22] opened 2017-03-03 03:10 UTC
hi @sabhiram 
I was running  this projec over raspberry pi 3 which is installed raspbian jessie.
I installed nodejs v7.7.1
When all prepare work has been done, I tried to run 'node server.js' but get an error,log is here : 
/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136
            info["hw_addr"].toLowerCase() == info["ap_addr"].toLowerCase() &&
                                                            ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at _is_ap_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136:61)
    at _is_wifi_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:115:28)
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:126:35
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:90:20
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:251:17
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:154:25
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:248:21
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:612:34
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:76:17
    at ChildProcess.exithandler (child_process.js:201:7)

do you have any idea about how to deal with this?
thank you

**Comment by sabhiram** [comment] 2017-03-03 06:18
This is a duplicate of #19. I think this is because iwconfig is not returning the expected fields to the script I wrote. I will see about reproducing this as time permits, unfortunately I am super busy at the moment w/ my work.

**Closed by sabhiram** 2017-03-03 06:18 UTC

**Comment by albertyou2** [comment] 2017-03-04 01:02
OK~thanks!
